### ISSUE TITLE
ReplaceSingleton for UserManager throws UnresolvedServicesException

### ISSUE THREAD

**Issue by mskurnik** [ivaylokenov/MyTested.AspNetCore.Mvc#252]
I attempted to create  a mock for the `UserManager<ApplicationUser>` singleton by creating a Mock class similar to how you created the `SignInMock` for the MusicStore example.
```
public class UserManagerMock : UserManager<ApplicationUser>
{
	public UserManagerMock(
		IUserStore<ApplicationUser> store,
		IOptions<IdentityOptions> optionsAccessor,
		IPasswordHasher<ApplicationUser> passwordHasher,
		IEnumerable<IUserValidator<ApplicationUser>> userValidators,
		IEnumerable<IPasswordValidator<ApplicationUser>> passwordValidators,
		ILookupNormalizer keyNormalizer,
		IdentityErrorDescriber errors,
		IServiceProvider services,
		ILogger<UserManager<ApplicationUser>> logger)
		: base(
			store, optionsAccessor, passwordHasher, userValidators, passwordValidators, keyNormalizer, errors,
			services, logger)
	{
	}
}

```

Whenever I add `services.ReplaceSingleton<UserManager<ApplicationUser>, UserManagerMock>();` to the `TestStartup.cs` class, the following exception is thrown:

```
An exception of type 'MyTested.AspNetCore.Mvc.Exceptions.UnresolvedServicesException' occurred in MyTested.AspNetCore.Mvc.Abstractions.dll but was not handled in user code

Additional information: HealthCheckController could not be instantiated because it contains no constructor taking no parameters.
```

The only way around this is to use the `WithServices(...)` extension method to specify all of the parameters for the constructor.  Commenting out the `ReplaceSingleton` method call allows the controller to be instantiated but then calling the `GetUserAsync` method (amongst others) from the `UserManager` class will return null.

**Comment by ivaylokenov** [comment]
@mskurnik May I see your `TestStartup` class, the unit test you are writing and the controller constructor?

With this mock, I am successfully instantiating a controller:

```c#
public class UserManagerMock : UserManager<ApplicationUser>
    {
        public UserManagerMock(
            IUserStore<ApplicationUser> store,
            IOptions<IdentityOptions> optionsAccessor,
            IPasswordHasher<ApplicationUser> passwordHasher,
            IEnumerable<IUserValidator<ApplicationUser>> userValidators,
            IEnumerable<IPasswordValidator<ApplicationUser>> passwordValidators,
            ILookupNormalizer keyNormalizer,
            IdentityErrorDescriber errors,
            IServiceProvider services,
            ILogger<UserManager<ApplicationUser>> logger)
            : base(store, optionsAccessor, passwordHasher, userValidators, passwordValidators, keyNormalizer, errors, services, logger)
        {
        }
    }
```

Ant this call in my `TestStartup` class:

```c#
services.ReplaceSingleton<UserManager<ApplicationUser>, UserManagerMock>();
```

I guess you are using version 1.0.0?

**Comment by mskurnik** [comment]
I am using 1.0.0.  My `TestStartup` is nothing special:
```C#
public class TestStartup : Startup
{
    public TestStartup(IHostingEnvironment env) : base(env) { }

    public void ConfigureTestServices(IServiceCollection services)
    {
        ConfigureServices(services);
        services.ReplaceSingleton<SignInManager<ApplicationUser>, SignInManagerMock>();
        services.ReplaceSingleton<UserManager<ApplicationUser>, UserManagerMock>();
    }
}
```

**Comment by ivaylokenov** [comment]
@mskurnik Mine too. What about the test and the controller constructor? With the above code, my tests are passing. Do you use any special dependency container? Do you use mixed `WithServices` call and not providing all constructor parameters?

**Comment by mskurnik** [comment]
OK.  I simplified my `HealthCheckController` for testing this.
```
public HealthCheckController(SignInManager<ApplicationUser> signInManager) { ... }
```
Now when I call the code below, I get the exception under it:
```C#
MyMvc
    .Controller<HealthCheckController>()
    .Calling(x => x.Index())
    .ShouldReturn()
    .Ok();
```

```
An exception of type 'MyTested.AspNetCore.Mvc.Exceptions.InvocationAssertionException' occurred in MyTested.AspNetCore.Mvc.Abstractions.dll but was not handled in user code

Additional information: When calling Index action in HealthCheckController expected no exception but AggregateException (containing NullReferenceException with 'Object reference not set to an instance of an object.' message) was thrown without being caught.
```

**Comment by ivaylokenov** [comment]
@mskurnik This exception shows that the actual action is run. You can put a break point in it and debug it to see what is null and what is not.

**Comment by mskurnik** [comment]
Yeah I just did.  I figured it out.  The `UserManager` is working as well as all the other dependency injected parameters.  During my debug of everything I added a null check for `User` that would throw a `NullReferenceException` if it was null.  Since I wasn't passing an authenticated user it was throwing the `NullReferenceException`.

**Comment by ivaylokenov** [comment]
@mskurnik Good to know! 👍
