### ISSUE TITLE
TestStartup doesn't work when to use ConfigureTest with IApplicationLifetime

### ISSUE THREAD

**Issue by kostyrin** [ivaylokenov/MyTested.AspNetCore.Mvc#256]
So,
I have code in the Startup
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IApplicationLifetime appLifetime)
        {
// some
}
```
 
I created TestStartup with method ConfigireTest.
code:
```
public void ConfigireTest(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IApplicationLifetime appLifetime)
        {
            base.Configure(app, env, loggerFactory, appLifetime);
        }
```

Then I have exception:
The type initializer for 'MyTested.AspNetCore.Mvc.MyController`1' threw an exception.
Could not resolve a service of type 'Microsoft.AspNetCore.Hosting.IApplicationLifetime' for the parameter 'appLifetime' of method 'Configure' on type 'Web.Startup'.
No service for type 'Microsoft.AspNetCore.Hosting.IApplicationLifetime' has been registered.

How to fix it?

**Comment by ivaylokenov** [comment]
This is my mistake. The framework should provide a built-in mock for the `IApplicationLifetime` interface. For now, you can fix the problem with Moq (or any custom implementation of the interface):

```c#
public class TestStartup : Startup
    {
        public TestStartup(IHostingEnvironment env) : base(env)
        {
        }

        public void ConfigureTest(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) // <--- Do not inject IApplicationLifetime
        {
            base.Configure(app, env, loggerFactory, Mock.Of<IApplicationLifetime>()); // <--- Provide your own implementation or a mock
        }
    }
```
