### ISSUE TITLE
Changing Test Project's default namespace breaks... test startup?

### ISSUE THREAD

**Issue by M-Adam** [ivaylokenov/MyTested.AspNetCore.Mvc#266]
Hello again :)
Not sure if its a bug, but here is how it can be reproduced.

I decided to reorganise namespaces in my test project. 
So I:

1. Right-clicked test project in Soultion Explorer
2. Change Default namespace (for example from "NetCoreShop.Test.Web" to "NetCoreShop.Test.Web.NamespaceChanged"

_At this moment everything works, including running tests, but namespaces in files are not set correctly - they are still pointing to "NetCoreShop.Test.Web"._

3.  Adjust namespaces in all files in project to "NetCoreShop.Test.Web.NamespaceChanged".
4. Clean and rebuild solution.
5. Run all tests. 

What happens:

![Image](http://image.prntscr.com/image/1bdec12e67984df681a52a261046633a.png)

```
Test Name:	NetCoreShop.Test.Web.NamespaceChanged.Controllers.AccountControllerTests.Login_Post_Fails_When_Password_Is_Invalid
Test FullName:	NetCoreShop.Test.Web.NamespaceChanged.Controllers.AccountControllerTests.Login_Post_Fails_When_Password_Is_Invalid
Test Source:	C:\Users\Adam\Desktop\ncs github\test\NetCoreShop.Test.Web\Controllers\AccountControllerTests.cs : line 369
Test Outcome:	Failed
Test Duration:	0:00:00,002

Result StackTrace:	
at MyTested.AspNetCore.Mvc.MyMvc.Controller[TController]()
   at NetCoreShop.Test.Web.NamespaceChanged.Controllers.AccountControllerTests.Login_Post_Fails_When_Password_Is_Invalid() in C:\Users\Adam\Desktop\ncs github\test\NetCoreShop.Test.Web\Controllers\AccountControllerTests.cs:line 378
   at MyTested.AspNetCore.Mvc.Internal.Application.TestApplication.TryInitialize()
   at MyTested.AspNetCore.Mvc.MyMvc..cctor()
Result Message:	
The type initializer for 'MyTested.AspNetCore.Mvc.MyMvc' threw an exception.
TestStartup class could not be found at the root of the test project. Either add it or set 'General.AutomaticStartup' in the test configuration ('testconfig.json' file by default) to 'false'.
```

I'm not using testconfig.json by the way.

Then I renamed the project itself to match the default namespace, but it did nothing.
What did help was manually changing name of the test project's folder to "NetCoreShop.Test.Web.NamespaceChanged" and editing solution .sln file
from
Project("{8BB2217D-0F2D-49D1-97BC-3654ED321F3B}") = "NetCoreShop.Test.Web.NamespaceChanged", "test\NetCoreShop.Test.Web\NetCoreShop.Test.Web.NamespaceChanged.xproj", "{5D650CA8-8370-4CB0-BB66-87E2C3339ED3}"
to
Project("{8BB2217D-0F2D-49D1-97BC-3654ED321F3B}") = "NetCoreShop.Test.Web.NamespaceChanged", "test\NetCoreShop.Test.Web.**NamespaceChanged**\NetCoreShop.Test.Web.NamespaceChanged.xproj", "{5D650CA8-8370-4CB0-BB66-87E2C3339ED3}".

Don't know if it's an issue with finding TestStartup or if it's an issue with changing namespaces in any .NET Core application.

If you wish, you can check it out on https://github.com/M-Adam/NetCoreShop (master)

**Comment by ivaylokenov** [comment]
@M-Adam You need to have the following two conditions in order for the `TestStartup` to be found (this is how reflection works in .NET Core). Let's say you use the `NetCoreShop` name:

1. The project's name must be `NetCoreShop`
2. The project's folder must be `NetCoreShop`
3. The startup file must be called `TestStartup` and it should be declared in the `NetCoreShop` namespace

In other words, project, folder and `TestStartup` namespace must have the same name.

If you are using `testconfig.json`, you can easily customize this default behavior. Let me know, if you need more information on that and I will explain. 👍

**Comment by M-Adam** [comment]
@ivaylokenov Wow, I wasn't aware that physical path on disk matters in .NET Core reflection. Thank you for explanations!

**Comment by ivaylokenov** [comment]
@M-Adam I believe it is because of the Roslyn compilation. I was too surprised to see it behave like that. 😄

**Comment by ivaylokenov** [comment]
@M-Adam If you want more information about the issue, check the `DependencyContext` class and what it does.
