### ISSUE TITLE
Question about requesting services without invoking MyMvc.Controller()

### ISSUE THREAD

**Issue by M-Adam** [ivaylokenov/MyTested.AspNetCore.Mvc#267]
So, I have 2 test projects that use MyTestedMvc library: Test.Web and Test.Services. Both have their own separate testconfig.json and TestStartup.cs files (they look the same so far, with the standard configuration, nothing fancy, just the licence code). In the first one I use MyMvc.Controller<Whatever>() everywhere to test controllers - works great. In the second one I'd like to test only services (as the will have more complex buisness logic) but also benefit from all the dependencies registered in TestStartupClass (especially repositories and DbContext :) ).

Simple example of hierarchy in main app project looks like that (for the record):
```csharp
public class UserController()
{ 
    private readonly IUserService _userService;
    public UserController(IUserService userService)
    {
        _userService = userService;
     }
    //....
}

public class UserService : IUserService
{
    private readonly IUserRepository _userRepository;
    private readonly IUnitOfWork _unitOfWork;
    public UserService (IUserRepository userRepository, IUnitOfWork unitOfWork)
    {
        _userRepository = userRepository;
        _unitOfWork = unitOfWork;
    }
    //... complex methods here
}

public class UserRepository : IUserRepository
{
    private readonly NetCoreShopContext _context;
    public UserRepository(NetCoreShopContext context)
    {
        _context = context;
    }
    //...
}
```

Example test could look like that:

```csharp
        [Fact]
        public void exaple()
        {
            User[] origUsers = {
                new User() {Username = "a"},
                new User() {Username = "b"},
                new User() {Username = "c"}
            };

            From.Services<NetCoreShopContext>().Users.AddRange(origUsers);

            var resultToTest = From.Services<IUserService>().GetAllUsers();

            Assert.Equal(origUsers, resultToTest);
        }
```
but on requesting DbContext it throws this:

```
An exception of type 'System.InvalidOperationException' occurred in MyTested.AspNetCore.Mvc.Abstractions.dll but was not handled in user code

Additional information: The test configuration ('testconfig.json' file by default) contained 'false' value for the 'General.NoStartup' option but a Startup class was not provided. Either add TestStartup class to the root of the test project or set it by calling 'StartsFrom<TStartup>()'. Additionally, if you do not want to use a global test application for all test cases in this project, you may change the test configuration option to 'true'.
```
However, TestStartup class is in place.

I've tried with calling
`MyMvc.StartsFrom<TestStartup>();`
a the very beginning but it threw
```
An exception of type 'System.InvalidOperationException' occurred in MyTested.AspNetCore.Mvc.Abstractions.dll but was not handled in user code

Additional information: Multiple Startup types per test project while running asynchronous tests is not supported. Either set 'General.AsynchronousTests' in the test configuration ('testconfig.json' file by default) to 'false' or separate your tests into different test projects. The latter is recommended. If you choose the first option, you may need to disable asynchronous testing in your preferred test runner too.
```

Finally I've worked it out like that:
```csharp
        [Fact]
        public void Get_All_Returns_All_Users()
        {
           object[] origUsers = {
                new User() {Username = "a"},
                new User() {Username = "b"},
                new User() {Username = "c"}
            };
            MyMvc.Controller<HomeController>()
                .WithDbContext(x => x.WithEntities(y => y.AddRange(origUsers)));

            var result = From.Services<IUserService>().GetAllUsers();

            Assert.Equal(origUsers, result);
        }
```
which works flawlessly, but I wanted to ask: is invoking controller mandatory to request registered service? Maybe there are some magic lines that can be put to testconfig.json? 😋

**Comment by ivaylokenov** [comment]
@M-Adam Can you upload the solution (or some minimal sample) so that I can look around? I am able to run multiple Startup files without any issue (for example the whole sample directory of this repository).

**Comment by M-Adam** [comment]
Of course, I've just pushed all changes to 
https://github.com/M-Adam/NetCoreShop (master)

**Comment by ivaylokenov** [comment]
@M-Adam This is my mistake and I will fix it in the next version. Problem is, every static class should try to initialize the test services when first called: https://github.com/ivaylokenov/MyTested.AspNetCore.Mvc/blob/development/src/MyTested.AspNetCore.Mvc.Controllers/MyController.cs#L16

I never expected anyone to call `From.Services` to test the services directly so this class does not have the necessary static constructor: https://github.com/ivaylokenov/MyTested.AspNetCore.Mvc/blob/development/src/MyTested.AspNetCore.Mvc.Abstractions/From.cs#L8

This is why you are receiving an error. You can work around it by calling `TestApplication.TryInitialize();` before the test (for example in the constructor of the test class).

I will fix this issue in the next version.

Also, in the future versions, I want to add built-in testing of services:

```c#
MyMvc
    .Service<IRepository>()
    .Calling(c => c.GetAll())
    .ShouldReturn<List<MyModel>>();
```

**Comment by M-Adam** [comment]
Yeah, I didn't see any usage of `From `class in the Tutorial the way I did it, so I was aware that it might not work as I expected 😄 
Thanks for quick response!

**Comment by ivaylokenov** [comment]
@M-Adam You are welcome! 👍
