### ISSUE TITLE
Routing tests do not pass with version specified in the url

### ISSUE THREAD

**Issue by TonyTroeff** [ivaylokenov/MyTested.AspNetCore.Mvc#358]
Recently, integrated versioning in my application through the "Microsoft.AspNetCore.Mvc.Versioning" package. I decided that it would be cool to add that API version to the requests` url as follows; "/api/v1/something_else" or "/api/v2/something_else" and so on.

This is a very basic controller that I created for testing purposes.
![image](https://user-images.githubusercontent.com/33567383/71601860-0809c680-2b5e-11ea-8a34-0ddeb0cf7c96.png)

And this is my routing test:
![image](https://user-images.githubusercontent.com/33567383/71601897-3daeaf80-2b5e-11ea-9177-98315196c0a9.png)

This is the information given after the test execution:
Message: MyTested.AspNetCore.Mvc.Exceptions.RouteAssertionException : Expected route '/api/v1/heartbeat' to match HeartBeat action in HeartBeatController but exception was thrown when trying to resolve route data: 'Object reference not set to an instance of an object.'.

![image](https://user-images.githubusercontent.com/33567383/71601972-98480b80-2b5e-11ea-9ce7-036337d2b753.png)

**Expected behavior** 
This test should pass. From postman I am able to get correct response:
![image](https://user-images.githubusercontent.com/33567383/71602143-77cc8100-2b5f-11ea-8f12-824f8eff2937.png)

**Startup classes**
My TestStartup class simply inherits StartUp. No additional configuratios have been made.

**Environment:**
 - Windows 10
 - ASP.NET Core 3.1

**Comment by ivaylokenov** [comment]
Thank you for reporting this issue, @TonyTroeff. I will investigate and deploy a fix as soon as possible.

**Comment by ivaylokenov** [comment]
@TonyTroeff I just published a new version, fixing this - 3.1.1. It is available on NuGet. You need to install the new plugin package in your test project - "MyTested.AspNetCore.Mvc.Versioning", and the version parts of the URL will start working correctly. I will close this issue when I merge the code.
