### ISSUE TITLE
When calling action expected result to be OkResult, but instead received T

### ISSUE THREAD

**Issue by TonyTroeff** [ivaylokenov/MyTested.AspNetCore.Mvc#359]
**Describe your issue**
My controller method returns `ActionResult<UserConstraintsViewModel>`.
This is my method:
![image](https://user-images.githubusercontent.com/33567383/71621681-64f69280-2bd9-11ea-9f5d-901f4d1e4669.png)

This is my test that validates this simple action:
![image](https://user-images.githubusercontent.com/33567383/71621700-8e172300-2bd9-11ea-8747-c3af5a9a5aff.png)

However, it does not pass. The exception message says: "MyTested.AspNetCore.Mvc.Exceptions.InvocationResultAssertionException : When calling UserConstraints action in ConstraintsController expected result to be OkResult, but instead received UserConstraintsViewModel."

**Expected behavior**
According to your documentation it is written correctly, so it is reasonable to pass.

**Startup classes**
My TestStartup class simply inherits StartUp. No additional configuratios have been made.

**Environment**
Windows 10
ASP.NET Core 3.1

**Comment by ivaylokenov** [comment]
@TonyTroeff, you can use `.ShouldReturn().Result(expectedModel)` with ActionResult<T> return types.

I will take a look to see how I can improve the error message to be friendlier.

**Comment by ivaylokenov** [comment]
@TonyTroeff I just published a new version, fixing this - 3.1.1. It is available on NuGet. Additionally, I added a new assertion chain, called `.ActionResult<TResult>()`, which allows to test `ActionResult<T>` easily. I will close the issue once I merge the code.
