### ISSUE TITLE
Controller attributes assertion does not include inherited ones

### ISSUE THREAD

**Issue by NaskoIT** [ivaylokenov/MyTested.AspNetCore.Mvc#366]
**More about the situation.**
In my code I have AdministrationBaseController which has ```Authorize``` and ```Area``` attributes
```[Authorize(Roles = GlobalConstants.AdministratorRoleName)]
	[Area(GlobalConstants.AdministrationArea)]
	public class AdministrationBaseController : BaseController
	{
	}
```
And then controllers in administration area inherit this class.
Something like this:
```public class ProblemController : AdministrationBaseController```

**Describe the solution you'd like**
I would like to be able to assert that ```ProblemController``` has ```Authorize``` and ```Area``` attributes.

**Comment by ivaylokenov** [comment]
Hi @NaskoVasilev! This suggestion is great. I will add it in the next release.
