### ISSUE TITLE
Task<ActionResult<TModel>> is not recognized correctly

### ISSUE THREAD

**Issue by ivaylokenov** [ivaylokenov/MyTested.AspNetCore.Mvc#370]
When the action result is Task<ActionResult<TModel>>, the task is not unwrapped.

**Comment by vickieallen** [comment]
Any update on when this will be done? As this is preventing us from being able to use your product currently.

**Comment by ivaylokenov** [comment]
@vickieallen A new version with a fix will be deployed by the end of this week. A possible workaround is:

```
.ShouldReturn()
.Object(result => result
    .WithModelOfType<ArticleDetailsOutputModel>()
    .Passing(model => model.Id == id && model.Author == TestUser.Username));
```

More samples are available in this repository: https://github.com/ivaylokenov/ASP.NET-Server-Architectures/blob/master/4.%20Clean%20Architecture%20On%20Steroids/tests/Web.IntegrationTests/Features/ArticlesControllerTests.cs

**Comment by vickieallen** [comment]
```
 MyMvc.Controller<AdvertController>()                     
                                     .WithUser(user => user
                                     .WithUsername("greg@getbrisk.com")
                                     .WithClaim(new Claim(ClaimTypes.Role, "Administrator"))
                                     .WithClaim(new Claim(ClaimTypes.Sid, "1"))
                                 )
                                 .Calling(c => c.CreateAdvertAsync(model))
                                .ShouldReturn()
                          .Object(result => result.WithModelOfType<AdvertViewModel>()
.Passing(e => e.Title == "Test Advert"));
```
 

This doesn't work for us as we're not returning an ObjectResult it would seem. I get the error  

MyTested.AspNetCore.Mvc.Exceptions.InvocationResultAssertionException: 'When calling CreateAdvertAsync action in AdvertController expected result to be ObjectResult, but instead received ActionResult<AdvertViewModel>.'

**Comment by ivaylokenov** [comment]
May I see the action `CreateAdvertAsync` code (or at least the return statements)?

**Comment by vickieallen** [comment]
```
 [HttpPost("advert")]
        public async Task<ActionResult<AdvertViewModel>> CreateAdvertAsync(AdvertViewModel advert)
        {
            var retVal = await _advertService.CreateAdvertAsync(advert);
            return Ok(retVal);
        }
```

**Comment by ivaylokenov** [comment]
@vickieallen Got it. And I guess `ShouldReturn().Ok(result => result.WithModel...)` is throwing the same error. Thank you for reporting. Will upload a fix to NuGet by the end of the week.

**Comment by vickieallen** [comment]
Yes it is throwing the same error, fantastic thank you! :)

**Comment by ivaylokenov** [comment]
@vickieallen the issue is now fixed, and a new version (3.1.2) is now published on NuGet. Let me know if you are facing any other problems.

**Comment by ivaylokenov** [comment]
@vickieallen Can you confirm that everything is working correctly with the latest version? Thank you!

**Comment by vickieallen** [comment]
Sorry! Yes this is all working now :) Thank you!
