### ISSUE TITLE
Testing POST overload

### ISSUE THREAD

**Issue by gkfischer** [ivaylokenov/MyTested.AspNetCore.Mvc#371]
I have a POST overload for e.g. the Create action of a controller that I would like to test. But my test ends up in the GET method. What I tried:
``` c#
MyController<ServicesController>
        .Instance()
        .WithHttpRequest(request => request
        .WithMethod(HttpMethod.Post)
        ...
```
The signatures in the controller are:
```  c#      
        public IActionResult Create()
```
and
```      c#  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Service service)
```
What did I miss?

**Comment by ivaylokenov** [comment]
Could you please show me some sample logic in the action? I am not sure what you are trying to assert? If you want to hit the second overload - you can say .Calling(c => c.Create(new Service())). If the service is from the DI container, you can say it like this - .Calling(c => c.Create(From.Services<Service>())).

**Comment by gkfischer** [comment]
Thanks for the hint, I was only using .Calling(c => c.Create()) instead of .Calling(c => c.Create(new Service())) and that was the resaon for the wrong controller action being called.
