### ISSUE TITLE
Assertion error when testing .NET Core WebApi

### ISSUE THREAD

**Issue by boojongmin** [ivaylokenov/MyTested.AspNetCore.Mvc#380]
hi, I'm .net core newbie.
I have trouble when ok assertion

#### my test code
![image](https://user-images.githubusercontent.com/9567723/82050155-99836a80-96f2-11ea-9114-76dfc3fc6cc9.png)

#### error message
```
 Message: 
    MyTested.AspNetCore.Mvc.Exceptions.InvocationResultAssertionException : When calling GetTodoItems action in TodoItemsController expected result to be OkResult, but instead received List<TodoItem>.
```

#### controller source

![image](https://user-images.githubusercontent.com/9567723/82050945-eddb1a00-96f3-11ea-8f15-b2f420aa2dbb.png)

thank you :)

**Comment by ivaylokenov** [comment]
You are returning a List of TodoItem and not an OK result. You need to use the `.Result` API:

```c#
.ShouldReturn()
.ResultOfType<List<TodoItem>>();
```

**Comment by boojongmin** [comment]
OMG!! 

spring framework does response 200 status when return object without throw exception.
I was think asp.net core also same that.

sorry I do close this isuue
